version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Egui family of crates need to go together.
      egui:
        patterns:
          - "egui*"
          - "eframe"
      reqwest:
        patterns:
          - "*reqwest*"
