[package]
name = "demo"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
walkers = { path = "../walkers" }
eframe.workspace = true
egui.workspace = true
egui_extras.workspace = true
