[package]
name = "wrowalk_web"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
wrowalk = { path = "../wrowalk" }
eframe.workspace = true
egui.workspace = true
log.workspace = true
wasm-bindgen-futures = "0.4"
web-sys = "0.3.70"
