[package]
name = "demo_native"
version.workspace = true
edition = "2021"
publish = false
default-run = "demo_native"

[dependencies]
wrowalk = { path = "../wrowalk" }
eframe.workspace = true
egui.workspace = true
env_logger = "0.11"
